### PR TITLE
🐛 fix(bug): float32 required for faiss

### PR DESCRIPTION
**Pull request by DylanAlloy**
我不确定这不是依赖版本控制问题或其他问题，但它解决了我创建硬底片的问题。

### CODE REVIEW

**Comment by staoxiao** [comment]
Thanks! This error is due to the current FlagModel default using fp16 for inference.

**Comment by DylanAlloy** [comment]
Ah this makes sense. only v1.5 or simply all were recently uploaded with fp16?

**Comment by staoxiao** [comment]
We just change the default value of `use_fp16`  to be `True` in https://github.com/FlagOpen/FlagEmbedding/blob/master/FlagEmbedding/flag_models.py#L16C32-L16C32 . 
Maybe it is not a necessary change.

**Comment by DylanAlloy** [comment]
Only reason I noticed is because I use fp32 on macbook MPS!
I think for GPU workloads this makes sense

**Pull request merged**
