### PR TITLE
[Feature] Add Ascend NPU support

### PR DESCRIPTION
**Pull request by huniu20**
What does this PR do?

Since ascend npu already supports Transformers/Accelerate and sentence-transformer out of the box, this would be a good addition to run FlagEmbedding out of the box on npu.

cc @staoxiao @namespace-Pt

### CODE REVIEW

**Comment by staoxiao** [comment]
Thanks~

**Comment by HANCHIE** [comment]
hello，do you have a example to run this embedding model on Ascend NPU? I can't find any example on internet.
 @huniu20 @staoxiao

**Comment by huniu20** [comment]
Just run the training or inference scripts in this repo in Ascend NPU device, if you encounter any problem, feel free to let me know:)

**Comment by statelesshz** [comment]
Hi @HANCHIE, you could try this patch directly, feel free to open an issue when encountering any problem and ping me or @huniu20 :-)

**Pull request merged**
